INSERT INTO countries (country, iso_2, flag_url) VALUES
    ('Albania', 'AL', 'https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg'),
    ('Andorra', 'AD', 'https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg'),
    ('Armenia', 'AM', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg'),
    ('Austria', 'AT', 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg'),
    ('Australia', 'AU', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg'),
    ('Azerbaijan', 'AZ', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg'),
    ('Bosnia and Herzegovina', 'BA', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg'),
    ('Belgium', 'BE', 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg'),
    ('Bulgaria', 'BG', 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg'),
    ('Belarus', 'BY', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg'),
    ('Switzerland', 'CH', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg'),
    ('Cyprus', 'CY', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg'),
    ('Czech Republic', 'CZ', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg'),
    ('Czechia', 'CZ', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg'),
    ('Germany', 'DE', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg'),
    ('Denmark', 'DK', 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg'),
    ('Estonia', 'EE', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg'),
    ('Spain', 'ES', 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg'),
    ('European Union', 'EU', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg'),
    ('Finland', 'FI', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg'),
    ('France', 'FR', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg'),
    ('United Kingdom', 'GB', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg'),
    ('Georgia', 'GE', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg'),
    ('Greece', 'GR', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg'),
    ('Croatia', 'HR', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg'),
    ('Hungary', 'HU', 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg'),
    ('Iceland', 'IS', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg'),
    ('Ireland', 'IE', 'https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg'),
    ('Israel', 'IL', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg'),
    ('Italy', 'IT', 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg'),
    ('Latvia', 'LV', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg'),
    ('Lithuania', 'LT', 'https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg'),
    ('Luxembourg', 'LU', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg'),
    ('Malta', 'MT', 'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg'),
    ('Moldova', 'MD', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg'),
    ('Monaco', 'MC', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg'),
    ('Montenegro', 'ME', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg'),
    ('Morocco', 'MA', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg'),
    ('Netherlands', 'NL', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg'),
    ('North Macedonia', 'MK', 'https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg'),
    ('Macedonia', 'MK', 'https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg'),
    ('Norway', 'NO', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg'),
    ('Poland', 'PL', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_Poland.svg'),
    ('Portugal', 'PT', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg'),
    ('Romania', 'RO', 'https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg'),
    ('Russia', 'RU', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg'),
    ('San Marino', 'SM', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg'),
    ('Serbia', 'RS', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg'),
    ('Serbia and Montenegro', null, 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Serbia_and_Montenegro_%281992%E2%80%932006%29.svg'),
    ('Slovakia', 'SK', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg'),
    ('Slovenia', 'SI', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg'),
    ('Sweden', 'SE', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg'),
    ('Turkey', 'TR', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg'),
    ('Ukraine', 'UA', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg'),
    ('Yugoslavia', null, 'https://upload.wikimedia.org/wikipedia/commons/6/61/Flag_of_Yugoslavia_%281946-1992%29.svg');