


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."esc_entries" (
    "id" bigint NOT NULL,
    "country" "text" NOT NULL,
    "year" smallint NOT NULL,
    "artist" "text" NOT NULL,
    "song_title" "text" NOT NULL,
    CONSTRAINT "esc_entries_year_check" CHECK ((("year" >= 1956) AND ("year" <= 9999)))
);


ALTER TABLE "public"."esc_entries" OWNER TO "postgres";


ALTER TABLE "public"."esc_entries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."esc_entries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."esc_real_scores" (
    "id" bigint NOT NULL,
    "entry_id" bigint NOT NULL,
    "is_final" boolean NOT NULL,
    "jury" smallint,
    "televote" smallint,
    "place" smallint,
    "running_order" smallint
);


ALTER TABLE "public"."esc_real_scores" OWNER TO "postgres";


ALTER TABLE "public"."esc_real_scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."esc_real_scores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pze_entries" (
    "id" bigint NOT NULL,
    "year" integer NOT NULL,
    "artist" "text" NOT NULL,
    "song_title" "text" NOT NULL,
    CONSTRAINT "pze_entries_year_check" CHECK ((("year" >= 2022) AND ("year" <= 9999)))
);


ALTER TABLE "public"."pze_entries" OWNER TO "postgres";


ALTER TABLE "public"."pze_entries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pze_entries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."esc_entries"
    ADD CONSTRAINT "esc_entries_akey" UNIQUE ("country", "year");



ALTER TABLE ONLY "public"."esc_entries"
    ADD CONSTRAINT "esc_entries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."esc_real_scores"
    ADD CONSTRAINT "esc_real_scores_akey" UNIQUE ("entry_id", "is_final");



ALTER TABLE ONLY "public"."esc_real_scores"
    ADD CONSTRAINT "esc_real_scores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pze_entries"
    ADD CONSTRAINT "pze_entries_akey" UNIQUE ("year", "artist");



ALTER TABLE ONLY "public"."pze_entries"
    ADD CONSTRAINT "pze_entries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."esc_real_scores"
    ADD CONSTRAINT "esc_real_scores_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."esc_entries"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."esc_entries" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."esc_real_scores" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."pze_entries" FOR SELECT USING (true);



ALTER TABLE "public"."esc_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."esc_real_scores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pze_entries" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."esc_entries" TO "anon";
GRANT ALL ON TABLE "public"."esc_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."esc_entries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."esc_entries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."esc_entries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."esc_entries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."esc_real_scores" TO "anon";
GRANT ALL ON TABLE "public"."esc_real_scores" TO "authenticated";
GRANT ALL ON TABLE "public"."esc_real_scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."esc_real_scores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."esc_real_scores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."esc_real_scores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pze_entries" TO "anon";
GRANT ALL ON TABLE "public"."pze_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."pze_entries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pze_entries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pze_entries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pze_entries_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


