alter table "public"."esc_entries" drop constraint "esc_entries_akey";

drop index if exists "public"."esc_entries_akey";


  create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "country" text not null,
    "iso_2" character(2),
    "flag_url" text
      );


alter table "public"."countries" enable row level security;

alter table "public"."esc_entries" drop column "country";

alter table "public"."esc_entries" add column "country_id" bigint not null;

CREATE UNIQUE INDEX countries_pkey ON public.countries USING btree (id);

CREATE UNIQUE INDEX unique_country ON public.countries USING btree (country);

CREATE UNIQUE INDEX esc_entries_akey ON public.esc_entries USING btree (country_id, year);

alter table "public"."countries" add constraint "countries_pkey" PRIMARY KEY using index "countries_pkey";

alter table "public"."countries" add constraint "unique_country" UNIQUE using index "unique_country";

alter table "public"."esc_entries" add constraint "esc_entries_country_id_fkey" FOREIGN KEY (country_id) REFERENCES public.countries(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."esc_entries" validate constraint "esc_entries_country_id_fkey";

alter table "public"."esc_entries" add constraint "esc_entries_akey" UNIQUE using index "esc_entries_akey";

grant select on table "public"."countries" to "anon";

grant delete on table "public"."countries" to "authenticated";

grant insert on table "public"."countries" to "authenticated";

grant select on table "public"."countries" to "authenticated";

grant update on table "public"."countries" to "authenticated";

grant delete on table "public"."countries" to "postgres";

grant insert on table "public"."countries" to "postgres";

grant references on table "public"."countries" to "postgres";

grant select on table "public"."countries" to "postgres";

grant trigger on table "public"."countries" to "postgres";

grant truncate on table "public"."countries" to "postgres";

grant update on table "public"."countries" to "postgres";

grant delete on table "public"."countries" to "service_role";

grant insert on table "public"."countries" to "service_role";

grant references on table "public"."countries" to "service_role";

grant select on table "public"."countries" to "service_role";

grant trigger on table "public"."countries" to "service_role";

grant truncate on table "public"."countries" to "service_role";

grant update on table "public"."countries" to "service_role";


  create policy "Enable read access for all users"
  on "public"."countries"
  as permissive
  for select
  to public
using (true);
