alter table "public"."countries"
    add column "heart_flag_url" text;

update "public"."countries" as c
set "heart_flag_url" = v."heart_flag_url"
from (
    values
        (1, 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Eurovision_2026_heart_-_Albania.svg'),
        (2, 'https://upload.wikimedia.org/wikipedia/commons/9/94/Eurovision_2026_heart_-_Andorra.svg'),
        (3, 'https://upload.wikimedia.org/wikipedia/commons/2/29/Eurovision_2026_heart_-_Armenia.svg'),
        (4, 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Eurovision_2026_heart_-_Austria.svg'),
        (5, 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Eurovision_2026_heart_-_Australia.svg'),
        (6, 'https://upload.wikimedia.org/wikipedia/commons/7/73/Eurovision_2026_heart_-_Azerbaijan.svg'),
        (7, 'https://upload.wikimedia.org/wikipedia/commons/8/89/Eurovision_2026_heart_-_Bosnia_and_Herzegovina.svg'),
        (8, 'https://upload.wikimedia.org/wikipedia/commons/7/76/Eurovision_2026_heart_-_Belgium.svg'),
        (9, 'https://upload.wikimedia.org/wikipedia/commons/3/31/Eurovision_2026_heart_-_Bulgaria.svg'),
        (10, 'https://upload.wikimedia.org/wikipedia/commons/2/26/Eurovision_2026_heart_-_Belarus.svg'),
        (11, 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Eurovision_2026_heart_-_Switzerland.svg'),
        (12, 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Eurovision_2026_heart_-_Cyprus.svg'),
        (13, 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Eurovision_2026_heart_-_Czechia.svg'),
        (14, 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Eurovision_2026_heart_-_Czechia.svg'),
        (15, 'https://upload.wikimedia.org/wikipedia/commons/3/37/Eurovision_2026_heart_-_Germany.svg'),
        (16, 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Eurovision_2026_heart_-_Denmark.svg'),
        (17, 'https://upload.wikimedia.org/wikipedia/commons/9/94/Eurovision_2026_heart_-_Estonia.svg'),
        (18, 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Eurovision_2026_heart_-_Spain.svg'),
        (19, 'https://upload.wikimedia.org/wikipedia/commons/0/01/Eurovision_2026_heart_-_Europe.svg'),
        (20, 'https://upload.wikimedia.org/wikipedia/commons/7/70/Eurovision_2026_heart_-_Finland.svg'),
        (21, 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Eurovision_2026_heart_-_France.svg'),
        (22, 'https://upload.wikimedia.org/wikipedia/commons/3/30/Eurovision_2026_heart_-_United_Kingdom.svg'),
        (23, 'https://upload.wikimedia.org/wikipedia/commons/1/13/Eurovision_2026_heart_-_Georgia.svg'),
        (24, 'https://upload.wikimedia.org/wikipedia/commons/4/46/Eurovision_2026_heart_-_Greece.svg'),
        (25, 'https://upload.wikimedia.org/wikipedia/commons/4/41/Eurovision_2026_heart_-_Croatia.svg'),
        (26, 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Eurovision_2026_heart_-_Hungary.svg'),
        (27, 'https://upload.wikimedia.org/wikipedia/commons/d/df/Eurovision_2026_heart_-_Iceland.svg'),
        (28, 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Eurovision_2026_heart_-_Ireland.svg'),
        (29, 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Eurovision_2026_heart_-_Israel.svg'),
        (30, 'https://upload.wikimedia.org/wikipedia/commons/3/31/Eurovision_2026_heart_-_Italy.svg'),
        (31, 'https://upload.wikimedia.org/wikipedia/commons/8/88/Eurovision_2026_heart_-_Latvia.svg'),
        (32, 'https://upload.wikimedia.org/wikipedia/commons/0/08/Eurovision_2026_heart_-_Lithuania.svg'),
        (33, 'https://upload.wikimedia.org/wikipedia/commons/5/51/Eurovision_2026_heart_-_Luxembourg.svg'),
        (34, 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Eurovision_2026_heart_-_Malta.svg'),
        (35, 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Eurovision_2026_heart_-_Moldova.svg'),
        (36, 'https://upload.wikimedia.org/wikipedia/commons/9/90/Eurovision_2026_heart_-_Monaco.svg'),
        (37, 'https://upload.wikimedia.org/wikipedia/commons/7/75/Eurovision_2026_heart_-_Montenegro.svg'),
        (38, 'https://upload.wikimedia.org/wikipedia/commons/1/19/Eurovision_2026_heart_-_Morocco.svg'),
        (39, 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Eurovision_2026_heart_-_Netherlands.svg'),
        (40, 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Eurovision_2026_heart_-_North_Macedonia.svg'),
        (41, 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Eurovision_2026_heart_-_North_Macedonia.svg'),
        (42, 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Eurovision_2026_heart_-_Norway.svg'),
        (43, 'https://upload.wikimedia.org/wikipedia/commons/3/37/Eurovision_2026_heart_-_Poland.svg'),
        (44, 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Eurovision_2026_heart_-_Portugal.svg'),
        (45, 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Eurovision_2026_heart_-_Romania.svg'),
        (46, 'https://upload.wikimedia.org/wikipedia/commons/8/84/Eurovision_2026_heart_-_Russia.svg'),
        (47, 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Eurovision_2026_heart_-_San_Marino.svg'),
        (48, 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Eurovision_2026_heart_-_Serbia.svg'),
        (49, 'https://upload.wikimedia.org/wikipedia/commons/0/03/Eurovision_2026_heart_-_Serbia_and_Montenegro.svg'),
        (50, 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Eurovision_2026_heart_-_Slovakia.svg'),
        (51, 'https://upload.wikimedia.org/wikipedia/commons/1/18/Eurovision_2026_heart_-_Slovenia.svg'),
        (52, 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Eurovision_2026_heart_-_Sweden.svg'),
        (53, 'https://upload.wikimedia.org/wikipedia/commons/9/93/Eurovision_2026_heart_-_Turkey.svg'),
        (54, 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Eurovision_2026_heart_-_Ukraine.svg'),
        (55, 'https://upload.wikimedia.org/wikipedia/commons/3/32/Eurovision_2026_heart_-_Yugoslavia.svg')
) AS v("id", "heart_flag_url")
WHERE c."id" = v."id";